package com.bytedance.sdk.openadsdk.rdp;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.ljh;
import com.bytedance.sdk.openadsdk.utils.ax;
import com.bytedance.sdk.openadsdk.utils.jtx;

/* JADX INFO: loaded from: classes6.dex */
public class exu extends com.bytedance.sdk.openadsdk.core.mo.wd {
    public exu(Context context) {
        this(context, null);
    }

    private void qdl(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        com.bytedance.sdk.openadsdk.core.mo.wd wdVar = new com.bytedance.sdk.openadsdk.core.mo.wd(context);
        wdVar.setId(jtx.gsp);
        wdVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        wdVar.setBackgroundColor(0);
        wdVar.setGravity(17);
        addView(wdVar);
        View mmlVar = new com.bytedance.sdk.openadsdk.core.mo.mml(context);
        mmlVar.setId(jtx.ygv);
        mmlVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        wdVar.addView(mmlVar);
        com.bytedance.sdk.openadsdk.core.mo.mo moVar = new com.bytedance.sdk.openadsdk.core.mo.mo(context);
        moVar.setId(jtx.hr);
        int iUd = ax.ud(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(iUd, iUd);
        layoutParams.addRule(13);
        moVar.setLayoutParams(layoutParams);
        moVar.setIndeterminateDrawable(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_video_loading_progress_bar"));
        wdVar.addView(moVar);
        com.bytedance.sdk.openadsdk.core.mo.mzz mzzVar = new com.bytedance.sdk.openadsdk.core.mo.mzz(context);
        mzzVar.setId(jtx.f17868se);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        mzzVar.setLayoutParams(layoutParams2);
        mzzVar.setGravity(1);
        mzzVar.setOrientation(1);
        mzzVar.setVisibility(8);
        wdVar.addView(mzzVar);
        com.bytedance.sdk.openadsdk.core.mo.mml mmlVar2 = new com.bytedance.sdk.openadsdk.core.mo.mml(context);
        mmlVar2.setId(jtx.f17870vc);
        mmlVar2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        mmlVar2.setImageDrawable(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_refreshing_video_textpage"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER;
        mmlVar2.setScaleType(scaleType);
        mzzVar.addView(mmlVar2);
        com.bytedance.sdk.openadsdk.core.mo.jpc jpcVar = new com.bytedance.sdk.openadsdk.core.mo.jpc(context);
        jpcVar.setId(jtx.fge);
        jpcVar.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        jpcVar.setText(ljh.qdl(context, "tt_video_retry_des_txt"));
        jpcVar.setTextColor(Color.parseColor("#999999"));
        mzzVar.addView(jpcVar);
        com.bytedance.sdk.openadsdk.core.mo.mml mmlVar3 = new com.bytedance.sdk.openadsdk.core.mo.mml(context);
        mmlVar3.setId(jtx.f17862hd);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        mmlVar3.setLayoutParams(layoutParams3);
        mmlVar3.setScaleType(scaleType);
        mmlVar3.setImageDrawable(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_play_movebar_textpage"));
        mmlVar3.setVisibility(8);
        addView(mmlVar3);
        com.bytedance.sdk.openadsdk.core.mo.mml mmlVar4 = new com.bytedance.sdk.openadsdk.core.mo.mml(context);
        mmlVar4.setId(jtx.hcs);
        int iUd2 = ax.ud(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(iUd2, iUd2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int iUd3 = ax.ud(context, 7.0f);
        layoutParams4.setMarginEnd(iUd3);
        layoutParams4.rightMargin = iUd3;
        layoutParams4.topMargin = iUd3;
        mmlVar4.setLayoutParams(layoutParams4);
        mmlVar4.setBackground(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_detail_video_btn_bg"));
        mmlVar4.setScaleType(scaleType);
        mmlVar4.setImageDrawable(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_close_move_detail"));
        addView(mmlVar4);
        com.bytedance.sdk.openadsdk.core.mo.jpc jpcVar2 = new com.bytedance.sdk.openadsdk.core.mo.jpc(context);
        jpcVar2.setId(jtx.kj);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        jpcVar2.setLayoutParams(layoutParams5);
        jpcVar2.setBackground(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        jpcVar2.setEllipsize(truncateAt);
        jpcVar2.setMaxLines(2);
        int iUd4 = ax.ud(context, 15.0f);
        jpcVar2.setPadding(iUd4, ax.ud(context, 14.0f), iUd4, 0);
        jpcVar2.setSingleLine(false);
        jpcVar2.setTextColor(-1);
        jpcVar2.setTextSize(2, 17.0f);
        jpcVar2.setVisibility(8);
        addView(jpcVar2);
        com.bytedance.sdk.openadsdk.core.mo.wd wdVar2 = new com.bytedance.sdk.openadsdk.core.mo.wd(context);
        wdVar2.setId(jtx.f17864od);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        wdVar2.setLayoutParams(layoutParams6);
        wdVar2.setBackground(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_video_black_desc_gradient"));
        wdVar2.setGravity(16);
        wdVar2.setVisibility(8);
        addView(wdVar2);
        com.bytedance.sdk.openadsdk.core.mo.mml mmlVar5 = new com.bytedance.sdk.openadsdk.core.mo.mml(context);
        int i10 = jtx.vm;
        mmlVar5.setId(i10);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int iUd5 = ax.ud(context, 12.0f);
        layoutParams7.leftMargin = iUd5;
        layoutParams7.setMarginStart(iUd5);
        mmlVar5.setLayoutParams(layoutParams7);
        mmlVar5.setScaleType(scaleType);
        mmlVar5.setImageDrawable(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_leftbackbutton_titlebar_photo_preview"));
        wdVar2.addView(mmlVar5);
        com.bytedance.sdk.openadsdk.core.mo.jpc jpcVar3 = new com.bytedance.sdk.openadsdk.core.mo.jpc(context);
        jpcVar3.setId(jtx.nts);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int iUd6 = ax.ud(context, 16.0f);
        layoutParams8.leftMargin = iUd6;
        layoutParams8.rightMargin = iUd;
        layoutParams8.setMarginStart(iUd6);
        layoutParams8.setMarginEnd(iUd);
        layoutParams8.addRule(17, i10);
        int i11 = jtx.eta;
        layoutParams8.addRule(0, i11);
        layoutParams8.addRule(1, i10);
        layoutParams8.addRule(16, i11);
        jpcVar3.setLayoutParams(layoutParams8);
        jpcVar3.setEllipsize(truncateAt);
        jpcVar3.setGravity(16);
        jpcVar3.setMaxLines(1);
        jpcVar3.setSingleLine(true);
        jpcVar3.setTextColor(-1);
        jpcVar3.setTextSize(2, 17.0f);
        wdVar2.addView(jpcVar3);
        com.bytedance.sdk.openadsdk.core.mo.mzz mzzVar2 = new com.bytedance.sdk.openadsdk.core.mo.mzz(context);
        mzzVar2.setId(i11);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int iUd7 = ax.ud(context, 14.0f);
        layoutParams9.rightMargin = iUd7;
        layoutParams9.setMarginEnd(iUd7);
        mzzVar2.setLayoutParams(layoutParams9);
        mzzVar2.setGravity(16);
        mzzVar2.setOrientation(1);
        wdVar2.addView(mzzVar2);
        com.bytedance.sdk.openadsdk.core.mo.jpc jpcVar4 = new com.bytedance.sdk.openadsdk.core.mo.jpc(context);
        jpcVar4.setId(jtx.vr);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        jpcVar4.setLayoutParams(layoutParams10);
        jpcVar4.setGravity(16);
        jpcVar4.setMaxLines(1);
        jpcVar4.setSingleLine(true);
        jpcVar4.setTextColor(-1);
        jpcVar4.setTextSize(2, 12.0f);
        mzzVar2.addView(jpcVar4);
        com.bytedance.sdk.openadsdk.core.mo.mzz mzzVar3 = new com.bytedance.sdk.openadsdk.core.mo.mzz(context);
        mzzVar3.setId(jtx.auu);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, ax.ud(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        mzzVar3.setLayoutParams(layoutParams11);
        mzzVar3.setGravity(16);
        mzzVar3.setOrientation(0);
        mzzVar3.setVisibility(8);
        addView(mzzVar3);
        com.bytedance.sdk.openadsdk.core.mo.jpc jpcVar5 = new com.bytedance.sdk.openadsdk.core.mo.jpc(context);
        jpcVar5.setId(jtx.gsv);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = iUd6;
        layoutParams12.rightMargin = iUd5;
        layoutParams12.setMarginEnd(iUd5);
        layoutParams12.setMarginStart(iUd6);
        jpcVar5.setLayoutParams(layoutParams12);
        jpcVar5.setText(ljh.qdl(context, "tt_00_00"));
        jpcVar5.setTextColor(-1);
        jpcVar5.setTextSize(2, 10.0f);
        mzzVar3.addView(jpcVar5);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(jtx.hvi);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, ax.ud(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_seek_progress"));
        seekBar.setThumb(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        mzzVar3.addView(seekBar);
        com.bytedance.sdk.openadsdk.core.mo.jpc jpcVar6 = new com.bytedance.sdk.openadsdk.core.mo.jpc(context);
        jpcVar6.setId(jtx.uvi);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = iUd5;
        layoutParams14.rightMargin = iUd6;
        layoutParams14.setMarginEnd(iUd6);
        layoutParams14.setMarginStart(iUd5);
        jpcVar6.setLayoutParams(layoutParams14);
        jpcVar6.setText(ljh.qdl(context, "tt_00_00"));
        jpcVar6.setTextColor(-1);
        jpcVar6.setTextSize(2, 10.0f);
        mzzVar3.addView(jpcVar6);
        com.bytedance.sdk.openadsdk.core.mo.mml mmlVar6 = new com.bytedance.sdk.openadsdk.core.mo.mml(context);
        mmlVar6.setId(jtx.oz);
        mmlVar6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        mmlVar6.setPadding(iUd6, 0, iUd6, 0);
        mmlVar6.setScaleType(scaleType);
        mmlVar6.setVisibility(8);
        mmlVar6.setImageDrawable(ljh.lnr(context, "tt_enlarge_video"));
        mzzVar3.addView(mmlVar6);
        View fsVar = new fs(context);
        fsVar.setId(jtx.syy);
        fsVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(fsVar);
        com.bytedance.sdk.openadsdk.core.mo.jpc jpcVar7 = new com.bytedance.sdk.openadsdk.core.mo.jpc(context);
        jpcVar7.setId(jtx.yre);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = iUd5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        jpcVar7.setLayoutParams(layoutParams15);
        jpcVar7.setBackgroundColor(Color.parseColor("#00000000"));
        jpcVar7.setText("close");
        jpcVar7.setMinHeight(ax.ud(context, 44.0f));
        jpcVar7.setCompoundDrawablesWithIntrinsicBounds(com.bytedance.sdk.openadsdk.utils.rq.qdl(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(jpcVar7);
    }

    public exu(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public exu(Context context, AttributeSet attributeSet, int i10) {
        super(context, attributeSet, i10);
        qdl(context);
    }
}
